version: "3"

services:
  nitter:
    build:
      context: .
      dockerfile: self-contained.Dockerfile
    ports:
      - "8081:8081"
    volumes:
      # should map this in PaaS
      - nitter-data:/nitter-data
    environment:
      # shuold be included for custom paths
      - NITTER_ACCOUNTS_FILE=/nitter-data/guest_accounts.json
      # optional instance custmizations from env
      - INSTANCE_TITLE=Custom title
      - INSTANCE_THEME=Twitter Dark
      - INSTANCE_INFINITE_SCROLL=1
    env_file:
      # should require from env
      # TWITTER_USERNAME
      # TWITTER_PASSWORD
      # INSTANCE_RSS_PASSWORD
      # INSTANCE_WEB_USERNAME
      # INSTANCE_WEB_PASSWORD
      - .env
volumes:
  nitter-data:
