app = 'nitter'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  dockerfile = 'fly.Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1

[[http_service.checks]]
    interval = '10s'
    timeout = '5s'
    grace_period = '30s'
    method = 'GET'
    path = '/'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
