# borrowed from
# https://github.com/PrivacyDevel/nitter/blob/master/.github/workflows/build-publish-docker.yml
name: Build and Publish Docker

on:
  push:
    branches: ["master"]
    paths-ignore: ["README.md"]
  pull_request:
    branches: ["master"]
    paths-ignore: ["README.md"]

env:
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
      - name: Build and push Docker image for self-contained variant
        uses: docker/build-push-action@v2
        with:
          context: .
          file: self-contained.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ github.repository_owner }}/nitter-self-contained:latest
          platforms: linux/amd64
  
  build-arm:
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm64
      - name: Build and push Docker image for self-contained variant
        uses: docker/build-push-action@v2
        with:
          context: .
          file: self-contained.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ github.repository_owner }}/nitter-self-contained:latest
          platforms: linux/arm64

  notify:
    runs-on: ubuntu-latest
    needs:
      - build
      - build-arm
    if: github.event_name == 'push'
    steps:
      - name: Send a Discord notification
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.github_token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
